// Code generated by go2go; DO NOT EDIT.


//line apply.go2:13
package filter

//line apply.go2:13
import (
//line apply.go2:13
 "reflect"
//line apply.go2:13
 "testing"
//line apply.go2:13
)

//line apply.go2:13
type Importable୦ int

//line apply.go2:13
var _ = reflect.Append
//line apply.go2:13
var _ = testing.AllocsPerRun
