// Code generated by go2go; DO NOT EDIT.


//line reduce.go2:5
package filter

//line reduce.go2:5
import (
//line reduce.go2:5
 "reflect"
//line reduce.go2:5
 "testing"
//line reduce.go2:5
)

//line reduce.go2:5
var _ = reflect.Append
//line reduce.go2:5
var _ = testing.AllocsPerRun
